apiVersion: v1
kind: Pod
metadata:
    name: microservice-libreria-pod
    labels:
        app: microservice-libreria
        type: microservice
spec:
    container:
    - name: microservice-libreria-app
      image: crakenasdocker/serviciosapilibreria:latest
      ports:
        - containerPort: 80
      env:
        - name: MongoDb__ConnectionString
          value: mongodb://vaxidrez:vaxidrez1234@mongo-service:27017
