apiVersion: apps/v1
kind: Deployment
metadata:
    name: microservice-seguridad-deploy
    labels:
        name: microservice-seguridad-deploy
        app: microservice
spec:
    replicas: 2
    selector:
        matchLabels:
            app: microservice-seguridad
            type: microservice
    template:
        metadata:
            name: microservice-seguridad-pod
            labels:
                app: microservice-seguridad
                type: microservice
        spec:
            container:
            - name: microservice-seguridad-app
              image: crakenasdocker/serviciosapiseguridad:v2.#{Build.BuildId}#
              ports:
                - containerPort: 80
              env:
                - name: ConnectionStrings__ConexionDB
                  value: Server_=mssql-service;Database=Seguridad;User=sa;Password=vaxidrez1234