apiVersion: v1
kind: Pod
metadata:
    name: mssql-pod
    labels:
            app: microservice-seguridad
            name: mssql-pod
spec:
    container:
    - name: mssql
      image: mcr.microsoft.com/misql/server
      ports:
        - containerPort: 80
      env:
      - name: ACCEPT_EULA
        value: "Y"
      - name: SA_PASSWORD
        value: "vaxidrez1234" 