apiVersion: apps/v1
kind: Deployment
metadata:
    name: mssql-deploy
    labels:
        name: mssql-deply
        app: microservice-seguridad
spec:
    replicas: 1
    selector:
        matchLabels:
            app: microservice-seguridad
            name: mssql-pod
    template:
        metadata:
            name: mssql-pod
            labels:
                    app: microservice-seguridad
                    name: mssql-pod
        spec:
            container:
            - name: mssql
              image: mcr.microsoft.com/misql/server
              ports:
                - containerPort: 80
              env:
              - name: ACCEPT_EULA
                value: "Y"
              - name: SA_PASSWORD
                value: "vaxidrez1234" 